language: python
python:
  - 3.6
# command to install dependencies
install:
  - cp contrib/env-sample .env
  - pip install -q -r requirements-dev.txt codecov
# command to run tests
script:
  - flake8 eventex
  - pytest --cov=eventex

after_success:
  - codecov