language: python
python:
  - "3.6"
# command to install dependencies
install:
  - cp contrib/env-sample .env
  - pip install -r requirements-dev.txt
# command to run tests
script:
  - flake8 eventex
  - py.test .